### ISSUE TITLE
Use dask

### ISSUE THREAD

**Issue by brisvag** [gutsche-lab/blik#120]
The first time we introduced lazy loading we tried with `dask.delayed`, but ultimately were trying to manually load the images when needed. Napari has pretty good handling of dask delayed now, and we should be able to simpoly load all the images as delayed and let napari handle everything!

Even better, this lets us use do cool thing like load trhough ssh :D

**Comment by alisterburt** [comment]
extra thoughts - are you suggesting we use something other than delayed? What juan showed was da.from_zarr, we can do da.from_delayed and pass that to napari, is that what you're suggesting?
